/*
##############################################################################
##
##  DO NOT REMOVE THIS LICENSE AND COPYRIGHT NOTICE FOR ANY REASON
##
##############################################################################

GNU VisualCTI - A Java multi-platform Computer Telephony Application Server
Copyright (C) 2002 by Oleg Sopilnyak.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Contact oleg.sopilnyak@gmail.com or gennady@visualcti.org for more information.

Ukraine point of contact: Oleg Sopilnyak - oleg.sopilnyak@gmail.com
Home Phone:	+380-63-8420220 (russian)

USA point of contact: Justin Kuntz - jkuntz@prominic.com
Prominic Technologies, Inc.
PO Box 3233
Champaign, IL 61826-3233
Fax number: 217-356-3356
##############################################################################

*/
/*
 * SecurityFrame.java
 *
 */

package org.visualcti.server.security;

import org.jdom.*;
import java.io.*;
import java.util.*;
import java.util.zip.*;
import org.visualcti.server.serverUnit;
/**
 * GUI for security manager
 * @author  Administrator
 */
public class SecurityFrame extends javax.swing.JFrame
{

    private transient volatile org.jdom.Element content = null;

    /** Creates new form SecurityFrame */
    public SecurityFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        rulePanel = new javax.swing.JPanel();
        permissionsPanel = new javax.swing.JPanel();
        eventsPermissionsPanel = new javax.swing.JPanel();
        eventsStartPermission = new javax.swing.JCheckBox();
        eventsStopPermission = new javax.swing.JCheckBox();
        eventsStatePermission = new javax.swing.JCheckBox();
        errorsPermissionsPanel = new javax.swing.JPanel();
        applyErrorsPermission = new javax.swing.JCheckBox();
        commandsPermissionsPanel = new javax.swing.JPanel();
        startCommandPermission = new javax.swing.JCheckBox();
        stopCommandPermission = new javax.swing.JCheckBox();
        getCommandPermission = new javax.swing.JCheckBox();
        setCommandPermission = new javax.swing.JCheckBox();
        responesPermissionsPanel = new javax.swing.JPanel();
        applyResponsePermision = new javax.swing.JCheckBox();
        selectionsControlPanel = new javax.swing.JPanel();
        selectAll_Permissions = new javax.swing.JButton();
        unSelectAll_Permissions = new javax.swing.JButton();
        ruleDescription = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ruleType = new javax.swing.JComboBox();
        serverUnitPath = new javax.swing.JLabel();
        controlButtons = new javax.swing.JPanel();
        OK = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        userGroupPanel = new javax.swing.JPanel();
        filterPanel = new javax.swing.JPanel();
        filterControlPanel = new javax.swing.JPanel();
        addFilterRule = new javax.swing.JButton();
        deleteFilterRule = new javax.swing.JButton();
        upFilterRule = new javax.swing.JButton();
        downFilterRule = new javax.swing.JButton();
        Filter = new javax.swing.JList();
        ActorsPanel = new javax.swing.JTabbedPane();
        GroupPanel = new javax.swing.JPanel();
        groupControlPanel = new javax.swing.JPanel();
        addGroup = new javax.swing.JButton();
        deleteGroup = new javax.swing.JButton();
        updateGroup = new javax.swing.JButton();
        groupIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        groupListPanel = new javax.swing.JPanel();
        groupDescritions = new javax.swing.JTextArea();
        groupList = new javax.swing.JList();
        UsersPanel = new javax.swing.JPanel();
        userControlPanel = new javax.swing.JPanel();
        addUser = new javax.swing.JButton();
        deleteUser = new javax.swing.JButton();
        updateUser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        userListPanel = new javax.swing.JPanel();
        usersList = new javax.swing.JList();
        userInformation = new javax.swing.JPanel();
        userInfoTitlesPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userInfoValuesPanel = new javax.swing.JPanel();
        userGroupInfo = new javax.swing.JTextField();
        userNameInfo = new javax.swing.JTextField();
        userContactInfo = new javax.swing.JTextField();
        userPassPanel = new javax.swing.JPanel();
        userPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        userPassword2 = new javax.swing.JPasswordField();

        setTitle("Server Security properties");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        rulePanel.setLayout(new java.awt.BorderLayout(3, 0));

        rulePanel.setBorder(new javax.swing.border.TitledBorder(null, "Permission's Rule", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 11), java.awt.Color.blue));
        rulePanel.setBackground(java.awt.Color.white);
        rulePanel.setDoubleBuffered(false);
        permissionsPanel.setLayout(new javax.swing.BoxLayout(permissionsPanel, javax.swing.BoxLayout.X_AXIS));

        eventsPermissionsPanel.setLayout(new java.awt.GridLayout(3, 1));

        eventsPermissionsPanel.setBorder(new javax.swing.border.TitledBorder(null, "events"));
        eventsPermissionsPanel.setDoubleBuffered(false);
        eventsStartPermission.setFont(new java.awt.Font("Dialog", 1, 10));
        eventsStartPermission.setText("start");
        eventsPermissionsPanel.add(eventsStartPermission);

        eventsStopPermission.setFont(new java.awt.Font("Dialog", 1, 10));
        eventsStopPermission.setText("stop");
        eventsPermissionsPanel.add(eventsStopPermission);

        eventsStatePermission.setFont(new java.awt.Font("Dialog", 1, 10));
        eventsStatePermission.setText("state");
        eventsPermissionsPanel.add(eventsStatePermission);

        permissionsPanel.add(eventsPermissionsPanel);

        errorsPermissionsPanel.setBorder(new javax.swing.border.TitledBorder("errors"));
        errorsPermissionsPanel.setDoubleBuffered(false);
        applyErrorsPermission.setFont(new java.awt.Font("Dialog", 1, 10));
        applyErrorsPermission.setText("apply");
        errorsPermissionsPanel.add(applyErrorsPermission);

        permissionsPanel.add(errorsPermissionsPanel);

        commandsPermissionsPanel.setLayout(new java.awt.GridLayout(4, 1));

        commandsPermissionsPanel.setBorder(new javax.swing.border.TitledBorder("commands"));
        commandsPermissionsPanel.setDoubleBuffered(false);
        startCommandPermission.setFont(new java.awt.Font("Dialog", 1, 10));
        startCommandPermission.setText("starting");
        commandsPermissionsPanel.add(startCommandPermission);

        stopCommandPermission.setFont(new java.awt.Font("Dialog", 1, 10));
        stopCommandPermission.setText("stopping");
        commandsPermissionsPanel.add(stopCommandPermission);

        getCommandPermission.setFont(new java.awt.Font("Dialog", 1, 10));
        getCommandPermission.setText("getting");
        commandsPermissionsPanel.add(getCommandPermission);

        setCommandPermission.setFont(new java.awt.Font("Dialog", 1, 10));
        setCommandPermission.setText("setting");
        commandsPermissionsPanel.add(setCommandPermission);

        permissionsPanel.add(commandsPermissionsPanel);

        responesPermissionsPanel.setBorder(new javax.swing.border.TitledBorder("responses"));
        applyResponsePermision.setFont(new java.awt.Font("Dialog", 1, 10));
        applyResponsePermision.setText("apply");
        responesPermissionsPanel.add(applyResponsePermision);

        permissionsPanel.add(responesPermissionsPanel);

        selectionsControlPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;

        selectionsControlPanel.setBorder(new javax.swing.border.TitledBorder("Selections control"));
        selectionsControlPanel.setDoubleBuffered(false);
        selectAll_Permissions.setToolTipText("to select all permissions");
        selectAll_Permissions.setFont(new java.awt.Font("Dialog", 0, 12));
        selectAll_Permissions.setText("select All");
        selectAll_Permissions.setPreferredSize(new java.awt.Dimension(81, 27));
        selectAll_Permissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAll_PermissionsActionPerformed(evt);
            }
        });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        selectionsControlPanel.add(selectAll_Permissions, gridBagConstraints1);

        unSelectAll_Permissions.setToolTipText("to clear selection for all permissions");
        unSelectAll_Permissions.setFont(new java.awt.Font("Dialog", 0, 12));
        unSelectAll_Permissions.setText("clear Selection");
        unSelectAll_Permissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unSelectAll_PermissionsActionPerformed(evt);
            }
        });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        selectionsControlPanel.add(unSelectAll_Permissions, gridBagConstraints1);

        permissionsPanel.add(selectionsControlPanel);

        rulePanel.add(permissionsPanel, java.awt.BorderLayout.CENTER);

        ruleDescription.setLayout(new java.awt.BorderLayout(3, 0));

        ruleDescription.setBackground(java.awt.Color.white);
        jLabel1.setText("Unit :");
        ruleDescription.add(jLabel1, java.awt.BorderLayout.WEST);

        ruleType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "allowed", "denied" }));
        ruleType.setMaximumRowCount(2);
        ruleType.setToolTipText("The rule for unit type");
        ruleType.setBackground(java.awt.Color.white);
        ruleType.setFont(new java.awt.Font("Monospaced", 1, 12));
        ruleDescription.add(ruleType, java.awt.BorderLayout.EAST);

        serverUnitPath.setText("/Server");
        serverUnitPath.setToolTipText("the path to unit in units registry");
        serverUnitPath.setForeground(java.awt.Color.blue);
        serverUnitPath.setFont(new java.awt.Font("Monospaced", 0, 14));
        ruleDescription.add(serverUnitPath, java.awt.BorderLayout.CENTER);

        rulePanel.add(ruleDescription, java.awt.BorderLayout.NORTH);

        getContentPane().add(rulePanel, java.awt.BorderLayout.SOUTH);

        controlButtons.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;

        controlButtons.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        //OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YES.gif")));
        OK.setToolTipText("to accept changes and close window");
        OK.setText("accept");
        OK.setPreferredSize(new java.awt.Dimension(90, 80));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.ipady = -50;
        gridBagConstraints2.insets = new java.awt.Insets(10, 0, 0, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTH;
        controlButtons.add(OK, gridBagConstraints2);

        //Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NO.gif")));
        Cancel.setToolTipText("to decline the changes and close window");
        Cancel.setText("cancel");
        Cancel.setPreferredSize(new java.awt.Dimension(90, 80));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 1;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.ipady = -50;
        gridBagConstraints2.insets = new java.awt.Insets(10, 0, 0, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTH;
        controlButtons.add(Cancel, gridBagConstraints2);

        getContentPane().add(controlButtons, java.awt.BorderLayout.EAST);

        userGroupPanel.setLayout(new java.awt.BorderLayout());

        userGroupPanel.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        filterPanel.setLayout(new java.awt.BorderLayout());

        filterControlPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 2));

        filterControlPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addFilterRule.setToolTipText("to add rule to filter");
        addFilterRule.setFont(new java.awt.Font("Dialog", 1, 14));
        addFilterRule.setText("+");
        addFilterRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFilterRuleActionPerformed(evt);
            }
        });

        filterControlPanel.add(addFilterRule);

        deleteFilterRule.setToolTipText("to delete rule from filter");
        deleteFilterRule.setFont(new java.awt.Font("Dialog", 1, 14));
        deleteFilterRule.setText("-");
        filterControlPanel.add(deleteFilterRule);

        upFilterRule.setToolTipText("to up rule in the filter");
        upFilterRule.setFont(new java.awt.Font("Dialog", 1, 14));
        upFilterRule.setText("^");
        filterControlPanel.add(upFilterRule);

        downFilterRule.setToolTipText("to down rule in filter");
        downFilterRule.setFont(new java.awt.Font("Dialog", 0, 14));
        downFilterRule.setText("v");
        filterControlPanel.add(downFilterRule);

        filterPanel.add(filterControlPanel, java.awt.BorderLayout.SOUTH);

        Filter.setToolTipText("List of Rules of Permissions");
        Filter.setBorder(new javax.swing.border.TitledBorder(null, "Filter", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 11), java.awt.Color.blue));
        Filter.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "/Service", "/Service/Messenger", "/Service/Messenger/EMAIL", "/Service/Log", "/Service/Security" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Filter.setForeground(java.awt.Color.blue);
        Filter.setFont(new java.awt.Font("Monospaced", 0, 12));
        Filter.setSelectedIndex(0);
        Filter.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        filterPanel.add(Filter, java.awt.BorderLayout.CENTER);

        userGroupPanel.add(filterPanel, java.awt.BorderLayout.EAST);

        ActorsPanel.setFont(new java.awt.Font("Monospaced", 0, 12));
        GroupPanel.setLayout(new java.awt.BorderLayout());

        groupControlPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        groupControlPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addGroup.setToolTipText("to add new Group");
        addGroup.setText("+");
        groupControlPanel.add(addGroup);

        deleteGroup.setToolTipText("to delete selected Group");
        deleteGroup.setText("-");
        groupControlPanel.add(deleteGroup);

        updateGroup.setToolTipText("to update selected Group");
        updateGroup.setText("update");
        groupControlPanel.add(updateGroup);

        GroupPanel.add(groupControlPanel, java.awt.BorderLayout.SOUTH);

        groupIcon.setPreferredSize(new java.awt.Dimension(3, 3));
        GroupPanel.add(groupIcon, java.awt.BorderLayout.EAST);

        jLabel3.setPreferredSize(new java.awt.Dimension(3, 3));
        GroupPanel.add(jLabel3, java.awt.BorderLayout.WEST);

        groupListPanel.setLayout(new java.awt.BorderLayout());

        groupDescritions.setLineWrap(true);
        groupDescritions.setEditable(false);
        groupDescritions.setRows(4);
        groupDescritions.setForeground(new java.awt.Color(102, 102, 153));
        groupDescritions.setText("Some text");
        groupDescritions.setBackground(java.awt.Color.lightGray);
        groupListPanel.add(groupDescritions, java.awt.BorderLayout.SOUTH);

        groupList.setBorder(new javax.swing.border.TitledBorder(null, "Description:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM));
        groupList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Administartors", "Servers", "Guests" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        groupList.setFont(new java.awt.Font("Dialog", 1, 12));
        groupList.setBackground(java.awt.Color.lightGray);
        groupList.setPreferredSize(new java.awt.Dimension(310, 181));
        groupList.setFixedCellWidth(300);
        groupList.setSelectedIndex(0);
        groupListPanel.add(groupList, java.awt.BorderLayout.CENTER);

        GroupPanel.add(groupListPanel, java.awt.BorderLayout.CENTER);

        ActorsPanel.addTab("Groups", GroupPanel);

        UsersPanel.setLayout(new java.awt.BorderLayout());

        userControlPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        userControlPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addUser.setToolTipText("to add new User");
        addUser.setText("+");
        userControlPanel.add(addUser);

        deleteUser.setToolTipText("to delete selected User");
        deleteUser.setText("-");
        userControlPanel.add(deleteUser);

        updateUser.setToolTipText("to update selected User");
        updateUser.setText("update");
        userControlPanel.add(updateUser);

        UsersPanel.add(userControlPanel, java.awt.BorderLayout.SOUTH);

        jLabel4.setPreferredSize(new java.awt.Dimension(3, 3));
        UsersPanel.add(jLabel4, java.awt.BorderLayout.WEST);

        userIcon.setPreferredSize(new java.awt.Dimension(3, 3));
        UsersPanel.add(userIcon, java.awt.BorderLayout.EAST);

        userListPanel.setLayout(new java.awt.BorderLayout());

        usersList.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        usersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Administartor", "localhost", "Guest" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        usersList.setFont(new java.awt.Font("Dialog", 1, 12));
        usersList.setPreferredSize(new java.awt.Dimension(310, 81));
        usersList.setFixedCellWidth(300);
        usersList.setSelectedIndex(0);
        usersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userListPanel.add(usersList, java.awt.BorderLayout.CENTER);

        userInformation.setLayout(new java.awt.BorderLayout());

        userInformation.setBorder(new javax.swing.border.TitledBorder(null, "User's Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        userInformation.setBackground(java.awt.Color.lightGray);
        userInfoTitlesPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 2));

        userInfoTitlesPanel.setBackground(java.awt.Color.lightGray);
        jLabel6.setText("Group:");
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setFont(new java.awt.Font("Dialog", 2, 12));
        userInfoTitlesPanel.add(jLabel6);

        jLabel7.setText("Full name:");
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setFont(new java.awt.Font("Dialog", 2, 12));
        userInfoTitlesPanel.add(jLabel7);

        jLabel8.setText("Contacts:");
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setFont(new java.awt.Font("Dialog", 2, 12));
        userInfoTitlesPanel.add(jLabel8);

        jLabel2.setText("Password:");
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12));
        userInfoTitlesPanel.add(jLabel2);

        userInformation.add(userInfoTitlesPanel, java.awt.BorderLayout.WEST);

        userInfoValuesPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 2));

        userGroupInfo.setEditable(false);
        userGroupInfo.setForeground(java.awt.Color.blue);
        userGroupInfo.setText("user's Group(s)");
        userInfoValuesPanel.add(userGroupInfo);

        userNameInfo.setEditable(false);
        userNameInfo.setForeground(java.awt.Color.blue);
        userNameInfo.setText("user's Full name");
        userInfoValuesPanel.add(userNameInfo);

        userContactInfo.setEditable(false);
        userContactInfo.setForeground(java.awt.Color.blue);
        userContactInfo.setText("user's Contacts");
        userInfoValuesPanel.add(userContactInfo);

        userPassword.setColumns(8);
        userPassword.setText("adm");
        userPassPanel.add(userPassword);

        jLabel5.setText(" Retype:");
        userPassPanel.add(jLabel5);

        userPassword2.setColumns(8);
        userPassword2.setText("adm");
        userPassPanel.add(userPassword2);

        userInfoValuesPanel.add(userPassPanel);

        userInformation.add(userInfoValuesPanel, java.awt.BorderLayout.CENTER);

        userListPanel.add(userInformation, java.awt.BorderLayout.SOUTH);

        UsersPanel.add(userListPanel, java.awt.BorderLayout.CENTER);

        ActorsPanel.addTab("Users", UsersPanel);

        userGroupPanel.add(ActorsPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(userGroupPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void addFilterRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFilterRuleActionPerformed
        Filter.setSelectedIndex(0);
    }//GEN-LAST:event_addFilterRuleActionPerformed

    private void unSelectAll_PermissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unSelectAll_PermissionsActionPerformed
        applyResponsePermision.setSelected(false);
        applyErrorsPermission.setSelected(false);
        eventsStartPermission.setSelected(false);
        eventsStopPermission.setSelected(false);
        eventsStatePermission.setSelected(false);
        startCommandPermission.setSelected(false);
        stopCommandPermission.setSelected(false);
        getCommandPermission.setSelected(false);
        setCommandPermission.setSelected(false);
    }//GEN-LAST:event_unSelectAll_PermissionsActionPerformed

    private void selectAll_PermissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAll_PermissionsActionPerformed
        applyResponsePermision.setSelected(true);
        applyErrorsPermission.setSelected(true);
        eventsStartPermission.setSelected(true);
        eventsStopPermission.setSelected(true);
        eventsStatePermission.setSelected(true);
        startCommandPermission.setSelected(true);
        stopCommandPermission.setSelected(true);
        getCommandPermission.setSelected(true);
        setCommandPermission.setSelected(true);
    }//GEN-LAST:event_selectAll_PermissionsActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        setVisible(false);
    }//GEN-LAST:event_OKActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        SecurityFrame GUI = new SecurityFrame();
        javax.swing.JFrame gui=null;
        try{
            FileOutputStream f = new FileOutputStream("work/SecurityFrame.gui");
            GZIPOutputStream zf = new GZIPOutputStream(f);
            ObjectOutputStream out = new ObjectOutputStream(zf);
            out.writeObject(GUI); out.flush(); out.close();
            FileInputStream fi = new FileInputStream("work/SecurityFrame.gui");
            GZIPInputStream zfi = new GZIPInputStream(fi);
            ObjectInputStream in = new ObjectInputStream(zfi);
            javax.swing.JFrame frame = (javax.swing.JFrame)in.readObject(); in.close();
            gui = new javax.swing.JFrame("Copy of Security system GUI");
            gui.getContentPane().add(frame.getRootPane(), java.awt.BorderLayout.CENTER);
            gui.pack();
        }catch(Exception e){
            e.printStackTrace();
        }
        if (gui != null) gui.setVisible(true);
        //GUI.show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rulePanel;
    private javax.swing.JPanel permissionsPanel;
    private javax.swing.JPanel eventsPermissionsPanel;
    private javax.swing.JCheckBox eventsStartPermission;
    private javax.swing.JCheckBox eventsStopPermission;
    private javax.swing.JCheckBox eventsStatePermission;
    private javax.swing.JPanel errorsPermissionsPanel;
    private javax.swing.JCheckBox applyErrorsPermission;
    private javax.swing.JPanel commandsPermissionsPanel;
    private javax.swing.JCheckBox startCommandPermission;
    private javax.swing.JCheckBox stopCommandPermission;
    private javax.swing.JCheckBox getCommandPermission;
    private javax.swing.JCheckBox setCommandPermission;
    private javax.swing.JPanel responesPermissionsPanel;
    private javax.swing.JCheckBox applyResponsePermision;
    private javax.swing.JPanel selectionsControlPanel;
    private javax.swing.JButton selectAll_Permissions;
    private javax.swing.JButton unSelectAll_Permissions;
    private javax.swing.JPanel ruleDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox ruleType;
    private javax.swing.JLabel serverUnitPath;
    private javax.swing.JPanel controlButtons;
    private javax.swing.JButton OK;
    private javax.swing.JButton Cancel;
    private javax.swing.JPanel userGroupPanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel filterControlPanel;
    private javax.swing.JButton addFilterRule;
    private javax.swing.JButton deleteFilterRule;
    private javax.swing.JButton upFilterRule;
    private javax.swing.JButton downFilterRule;
    private javax.swing.JList Filter;
    private javax.swing.JTabbedPane ActorsPanel;
    private javax.swing.JPanel GroupPanel;
    private javax.swing.JPanel groupControlPanel;
    private javax.swing.JButton addGroup;
    private javax.swing.JButton deleteGroup;
    private javax.swing.JButton updateGroup;
    private javax.swing.JLabel groupIcon;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel groupListPanel;
    private javax.swing.JTextArea groupDescritions;
    private javax.swing.JList groupList;
    private javax.swing.JPanel UsersPanel;
    private javax.swing.JPanel userControlPanel;
    private javax.swing.JButton addUser;
    private javax.swing.JButton deleteUser;
    private javax.swing.JButton updateUser;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel userIcon;
    private javax.swing.JPanel userListPanel;
    private javax.swing.JList usersList;
    private javax.swing.JPanel userInformation;
    private javax.swing.JPanel userInfoTitlesPanel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel userInfoValuesPanel;
    private javax.swing.JTextField userGroupInfo;
    private javax.swing.JTextField userNameInfo;
    private javax.swing.JTextField userContactInfo;
    private javax.swing.JPanel userPassPanel;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField userPassword2;
    // End of variables declaration//GEN-END:variables

}
