/*
##############################################################################
##
##  DO NOT REMOVE THIS LICENSE AND COPYRIGHT NOTICE FOR ANY REASON
##
##############################################################################

GNU VisualCTI - A Java multi-platform Computer Telephony Application Server
Copyright (C) 2002 by Oleg Sopilnyak.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Contact oleg@visualcti.org or gennady@visualcti.org for more information.

Ukraine point of contact: Oleg Sopilnyak - oleg@visualcti.org
Home Phone:	380-62-3851086 (russian)

USA point of contact: Justin Kuntz - jkuntz@prominic.com
Prominic Technologies, Inc.
PO Box 3233
Champaign, IL 61826-3233
Fax number: 217-356-3356
##############################################################################

*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visualcti_server_hardware_provider_dialogic_Hardware */

#ifndef _Included_org_visualcti_server_hardware_provider_dialogic_Hardware
#define _Included_org_visualcti_server_hardware_provider_dialogic_Hardware
#ifdef __cplusplus
extern "C" {
#endif
#undef org_visualcti_server_hardware_provider_dialogic_Hardware_DX_ERROR
#define org_visualcti_server_hardware_provider_dialogic_Hardware_DX_ERROR -1L
#undef org_visualcti_server_hardware_provider_dialogic_Hardware_DX_ONHOOK
#define org_visualcti_server_hardware_provider_dialogic_Hardware_DX_ONHOOK 0L
#undef org_visualcti_server_hardware_provider_dialogic_Hardware_DX_OFFHOOK
#define org_visualcti_server_hardware_provider_dialogic_Hardware_DX_OFFHOOK 1L
/* Inaccessible static: DEBUG */
/* Inaccessible static: ERROR */
/* Inaccessible static: class_00024org_00024visualcti_00024server_00024hardware_00024provider_00024dialogic_00024Hardware */
/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    getNamesList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_getNamesList
  (JNIEnv *, jclass);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_init
  (JNIEnv *, jclass);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    disableEvents
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_disableEvents
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    enableEvents
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_enableEvents
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    isCallAlerted
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_isCallAlerted
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    getCallerID
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_getCallerID
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    call
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_call
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    openFax
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_openFax
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    getEvent
 * Signature: ()Lorg/visualcti/server/hardware/provider/dialogic/dialogicEvent;
 */
JNIEXPORT jobject JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_getEvent
  (JNIEnv *, jclass);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    setHook
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_setHook
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    stopAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_stopAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_visualcti_server_hardware_provider_dialogic_Hardware
 * Method:    errorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_visualcti_server_hardware_provider_dialogic_Hardware_errorMessage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
