/*
##############################################################################
##
##  DO NOT REMOVE THIS LICENSE AND COPYRIGHT NOTICE FOR ANY REASON
##
##############################################################################

GNU VisualCTI - A Java multi-platform Computer Telephony Application Server
Copyright (C) 2002 by Oleg Sopilnyak.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Contact oleg@visualcti.org or gennady@visualcti.org for more information.

Ukraine point of contact: Oleg Sopilnyak - oleg@visualcti.org
Home Phone:	380-62-3851086 (russian)

USA point of contact: Justin Kuntz - jkuntz@prominic.com
Prominic Technologies, Inc.
PO Box 3233
Champaign, IL 61826-3233
Fax number: 217-356-3356
##############################################################################

*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visualcti_server_hardware_provider_dialogic_FAX */

#ifndef _Included_org_visualcti_server_hardware_provider_dialogic_FAX
#define _Included_org_visualcti_server_hardware_provider_dialogic_FAX
#ifdef __cplusplus
extern "C" {
#endif
#undef org_visualcti_server_hardware_provider_dialogic_FAX_DF_RX
#define org_visualcti_server_hardware_provider_dialogic_FAX_DF_RX 0L
#undef org_visualcti_server_hardware_provider_dialogic_FAX_DF_TX
#define org_visualcti_server_hardware_provider_dialogic_FAX_DF_TX 1L
	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    isSupport
	 * Signature: (I)Z
	 */
JNIEXPORT jboolean JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_isSupport
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    GetTransferredPages
	 * Signature: (I)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_GetTransferredPages
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    SetLocalID
	 * Signature: (ILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_SetLocalID
  (JNIEnv *, jclass, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    SetRemoteID
	 * Signature: (ILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_SetRemoteID
  (JNIEnv *, jclass, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    SetHeaderInfo
	 * Signature: (ILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_SetHeaderInfo
  (JNIEnv *, jclass, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    SetDateTime
	 * Signature: (ILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_SetDateTime
  (JNIEnv *, jclass, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    SetStartPage
	 * Signature: (II)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_SetStartPage
  (JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    InitRecieveState
	 * Signature: (I)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_InitRecieveState
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    InitTransmitState
	 * Signature: (I)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_InitTransmitState
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    StartRecieve
	 * Signature: (ILjava/lang/String;Z)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_StartRecieve
  (JNIEnv *, jclass, jint, jstring, jboolean);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_FAX
	 * Method:    StartSend
	 * Signature: (IZLjava/lang/String;ZZII)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_FAX_StartSend
  (JNIEnv *, jclass, jint, jboolean, jstring, jboolean, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
