/*
##############################################################################
##
##  DO NOT REMOVE THIS LICENSE AND COPYRIGHT NOTICE FOR ANY REASON
##
##############################################################################

GNU VisualCTI - A Java multi-platform Computer Telephony Application Server
Copyright (C) 2002 by Oleg Sopilnyak.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Contact oleg@visualcti.org or gennady@visualcti.org for more information.

Ukraine point of contact: Oleg Sopilnyak - oleg@visualcti.org
Home Phone:	380-62-3851086 (russian)

USA point of contact: Justin Kuntz - jkuntz@prominic.com
Prominic Technologies, Inc.
PO Box 3233
Champaign, IL 61826-3233
Fax number: 217-356-3356
##############################################################################

*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visualcti_server_hardware_provider_dialogic_SCBUS */

#ifndef _Included_org_visualcti_server_hardware_provider_dialogic_SCBUS
#define _Included_org_visualcti_server_hardware_provider_dialogic_SCBUS
#ifdef __cplusplus
extern "C" {
#endif
#undef org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_VOX
#define org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_VOX 1L
#undef org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_LSI
#define org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_LSI 2L
#undef org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_DTI
#define org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_DTI 3L
#undef org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_FAX
#define org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_FAX 4L
#undef org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_MSI
#define org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_MSI 5L
#undef org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_FULLDUP
#define org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_FULLDUP 0L
#undef org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_HALFDUP
#define org_visualcti_server_hardware_provider_dialogic_SCBUS_SC_HALFDUP 1L
	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_SCBUS
	 * Method:    isSupport
	 * Signature: (I)Z
	 */
JNIEXPORT jboolean JNICALL Java_org_visualcti_server_hardware_provider_dialogic_SCBUS_isSupport
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_SCBUS
	 * Method:    txTimeslot
	 * Signature: (II)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_SCBUS_txTimeslot
  (JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_SCBUS
	 * Method:    attach
	 * Signature: (III)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_SCBUS_attach
  (JNIEnv *, jclass, jint, jint, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_SCBUS
	 * Method:    detach
	 * Signature: (II)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_SCBUS_detach
  (JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_SCBUS
	 * Method:    connect
	 * Signature: (IIII)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_SCBUS_connect
  (JNIEnv *, jclass, jint, jint, jint, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_SCBUS
	 * Method:    disconnect
	 * Signature: (IIII)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_SCBUS_disconnect
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
