/*
##############################################################################
##
##  DO NOT REMOVE THIS LICENSE AND COPYRIGHT NOTICE FOR ANY REASON
##
##############################################################################

GNU VisualCTI - A Java multi-platform Computer Telephony Application Server
Copyright (C) 2002 by Oleg Sopilnyak.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Contact oleg@visualcti.org or gennady@visualcti.org for more information.

Ukraine point of contact: Oleg Sopilnyak - oleg@visualcti.org
Home Phone:	380-62-3851086 (russian)

USA point of contact: Justin Kuntz - jkuntz@prominic.com
Prominic Technologies, Inc.
PO Box 3233
Champaign, IL 61826-3233
Fax number: 217-356-3356
##############################################################################

*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visualcti_server_hardware_provider_dialogic_VOX */

#ifndef _Included_org_visualcti_server_hardware_provider_dialogic_VOX
#define _Included_org_visualcti_server_hardware_provider_dialogic_VOX
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    isSupport
	 * Signature: (I)Z
	 */
JNIEXPORT jboolean JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_isSupport
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    getCodecsList
	 * Signature: (I)Ljava/lang/String;
	 */
JNIEXPORT jstring JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_getCodecsList
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    startRecord
	 * Signature: (ILjava/lang/String;IILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_startRecord
  (JNIEnv *, jclass, jint, jstring, jint, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    startPlay
	 * Signature: (ILjava/lang/String;ILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_startPlay
  (JNIEnv *, jclass, jint, jstring, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    dial
	 * Signature: (ILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_dial
  (JNIEnv *, jclass, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    generateTone
	 * Signature: (IIII)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_generateTone
  (JNIEnv *, jclass, jint, jint, jint, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    digitsBuffer
	 * Signature: (I)Ljava/lang/String;
	 */
JNIEXPORT jstring JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_digitsBuffer
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    getDigit
	 * Signature: (II)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_getDigit
  (JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    clearTones
	 * Signature: (I)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_clearTones
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    setTone
	 * Signature: (ILjava/lang/String;)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_setTone
  (JNIEnv *, jclass, jint, jstring);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    fixTones
	 * Signature: (I)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_fixTones
  (JNIEnv *, jclass, jint);

	/*
	 * Class:     org_visualcti_server_hardware_provider_dialogic_VOX
	 * Method:    toneDetect
	 * Signature: (ILjava/lang/String;Z)I
	 */
JNIEXPORT jint JNICALL Java_org_visualcti_server_hardware_provider_dialogic_VOX_toneDetect
  (JNIEnv *, jclass, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
